# Generated by Django 2.1.7 on 2019-04-05 00:07

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20190403_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=feed.models.upload_to),
        ),
    ]
